name: MinIO
version: "1.1.0"
description: High performance, self-hosted S3 storage server for backups and object storage
slug: minio
startup: services
boot: auto
init: false

advanced: true
panel_icon: mdi:server-network
panel_title: MinIO
url: "http://[HOST]:[PORT:9001]"

host_network: false
homeassistant_api: false
hassio_api: false

privileged:
  - NET_ADMIN
  - SYS_ADMIN

map:
  - config:rw
  - ssl
  - share:rw
  - media:rw
  - backup:rw
  - addons:rw

options:
  generate_keys: false
  username: "admin"
  password: "minio123"
  access_key: ""
  secret_key: ""
  port: 9000
  console_port: 9001
  enable_ssl: false
  storage_path: "/data/minio"

schema:
  generate_keys: bool
  username: str?
  password: str?
  access_key: str?
  secret_key: str?
  port: int
  console_port: int
  enable_ssl: bool
  storage_path: str

ports:
  "9000/tcp": 9000
  "9001/tcp": 9001

arch:
  - aarch64
  - amd64

watchdog: "http://[HOST]:[PORT:9001]/minio/health/live"
