name: MinIO
version: "1.1.0"
slug: minio
description: High performance, self-hosted S3 storage server for backups and object storage
startup: services
boot: auto
init: false
advanced: true
watchdog: "http://[HOST]:[PORT:9001]/minio/health/live"
url: "http://[HOST]:[PORT:9001]"
panel_icon: mdi:server-network
panel_title: MinIO

host_network: false
homeassistant_api: false
hassio_api: false

privileged:
  - NET_ADMIN
  - SYS_ADMIN

arch:
  - aarch64
  - amd64

ports:
  "9000/tcp": 9000
  "9001/tcp": 9001

map:
  - config:rw
  - ssl
  - backup:rw
  - share:rw
  - media:rw

options:
  username: "admin"
  password: "minio123"
  access_key: ""
  secret_key: ""
  port: 9000
  console_port: 9001
  enable_ssl: false
  enable_redirect: false
  storage_path: "/data/minio"

schema:
  username: str?
  password: str?
  access_key: str?
  secret_key: str?
  port: port
  console_port: port
  enable_ssl: bool
  enable_redirect: bool
  storage_path: str
