name: MinIO
version: "1.1.0"
slug: minio
description: High performance, self-hosted S3 storage server for backups and object storage
arch:
  - aarch64
  - amd64
startup: services
boot: auto
init: false
advanced: true

ports:
  "9000/tcp": 9000
  "9001/tcp": 9001
ports_description:
  "9000/tcp": "S3 API endpoint"
  "9001/tcp": "MinIO Console"

url: "https://github.com/watsonpaul80/hassio-addons/tree/main/minio"
webui: "http://[HOST]:[PORT:9001]"
watchdog: "http://[HOST]:[PORT:9001]/minio/health/live"

panel_icon: mdi:server-network
panel_title: MinIO
panel_admin: true

map:
  - config:rw
  - ssl
  - addons:rw
  - backup:rw
  - share:rw
  - media:rw

privileged:
  - NET_ADMIN
  - SYS_ADMIN

options:
  access_key: "admin"
  secret_key: "minio123"
  port: 9000
  console_port: 9001
  storage_path: "/data/minio"

schema:
  access_key: str
  secret_key: str
  port: int
  console_port: int
  storage_path: str

