name: MinIO
version: "1.0.6"
description: High performance, self-hosted S3 storage server for backups and object storage
slug: minio
startup: services
boot: auto
init: false

ingress: true
ingress_port: 9001
panel_icon: mdi:server-network
panel_title: MinIO

host_network: false
homeassistant_api: false
hassio_api: false

privileged:
  - NET_ADMIN
  - SYS_ADMIN

options:
  generate_keys: true
  username: "admin"
  password: "minio123"
  port: 9000
  console_port: 9001

schema:
  generate_keys: bool
  username: str?
  password: str?
  port: int
  console_port: int

map:
  - config:rw
  - ssl
  - addons:rw
  - backup:rw
  - share:rw
  - media:rw

ports:
  "9001/tcp": 9001

arch:
  - aarch64
  - amd64
